web assignment team 5/Controllers/FlightController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using web_assignment_team_5.DAL;
using web_assignment_team_5.Models;

namespace web_assignment_team_5.Controllers
{
    public class FlightController : Controller
    {

        private FlightScheduleDAL flightScheduleContext = new FlightScheduleDAL();
        private FlightRouteDAL flightRouteContext = new FlightRouteDAL();
        private List<SelectListItem> ArrivalFlightCountry = new List<SelectListItem>();
        private List<SelectListItem> DepartureFlightCountry = new List<SelectListItem>();
        private List<SelectListItem> ArrivalFlightCity = new List<SelectListItem>();
        private List<SelectListItem> DepartureFlightCity = new List<SelectListItem>();
        private FlightScheduleDAL flightscheduleContext = new FlightScheduleDAL();
        private AircraftDAL aircraftContext = new AircraftDAL();
        FlightRouteDAL flightrouteContext = new FlightRouteDAL();

        public IActionResult Index()
        {
            // Stop accessing the action if not logged in 
            // or account not in the "Admin" role 
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }

            List<FlightSchedule> flightList = flightScheduleContext.GetAllFlightSchedule();
            return View(flightList);
        }


        //GET All flightroute
        //Get all flight scedhule and assign to each route
        public ActionResult Viewflights()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }

            List<FlightRoute> flightList = flightrouteContext.GetAllFlightRoutes();

            for (int i = 0; i < flightList.Count; i++)
            {
                flightList[i].flightSchedules = flightscheduleContext.GetRouteIDFlightSchedule(flightList[i].RouteID);
            }
            return View(flightList);
        }

       //get a drop down list containing routeid
       private List<SelectListItem> GetRouteID()
        {
            List<FlightRoute> routeList = flightrouteContext.GetAllFlightRoutes();
            List<SelectListItem> routeIDList = new List<SelectListItem>();
            foreach(FlightRoute item in routeList)
            {
                routeIDList.Add(new SelectListItem {Value = item.RouteID.ToString(),Text =item.RouteID.ToString() } );
            }
            return routeIDList;
        }
        //to update the status
        public ActionResult Update(int? id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            { //Query string parameter not provided 
                //Return to listing page, not allowed to edit 
                return RedirectToAction("Index");
            }
            FlightSchedule flight = flightscheduleContext.GetDetails(id.Value);
            if (flight == null)
            { //Return to listing page, not allowed to edit 
                return RedirectToAction("Index");
            }
            return View(flight);
        }
        //posting the changes
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(FlightSchedule flight)
        {
            if (ModelState.IsValid)
            {
                flightscheduleContext.Update(flight);
                return RedirectToAction("Viewflights");
            }
            else
            {
                //validation fail, return to view
                return View(flight);
            }
        }

        // GET: FlightController/Create
        public ActionResult CreateRoute()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        // GET: FlightController/Create
        // POST: FlightController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRoute(FlightRoute flightRoute)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }


            int routeID = flightrouteContext.CreateRoute(flightRoute);
            if (routeID != 0)
            {
                ModelState.AddModelError("Route", "Successfully created and assigned to " + routeID);
            }
            return View();
        }

        // GET: FlightController/Create
        // POST: FlightController/Create
        public ActionResult CreateSchedule()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            ViewData["RouteIDList"] = GetRouteID();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSchedule(FlightSchedule flightSchedule)
        {

            ViewData["RouteIDList"] = GetRouteID();
            if (ModelState.IsValid)
            {
                flightSchedule.ScheduleID=flightscheduleContext.CreateSchedule(flightSchedule);
                return RedirectToAction("Viewflights");
            }
            else
            {
                //validation fail, return to view
                return View(flightSchedule);
            }
        }



        //Get: FlightController/details/5

        public IActionResult FlightSchedule(int id)
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("ViewSchedule");
            }
            FlightSchedule f = flightScheduleContext.GetDetails(id);
            FlightScheduleViewModel flightVM = MapToflightVM(f);
            return View(flightVM);
        }
        
        public FlightScheduleViewModel MapToflightVM(FlightSchedule flight)
        {
            List<int> tempAircraftId = new List<int>();
            List<string> tempAircraftStatus = new List<string>();
            List<DateTime> tempDepartureDateTime = new List<DateTime>();
            List<DateTime> tempArrivalDateTime = new List<DateTime>();
            List<string> tempDepartureFlightCountry = new List<string>();
            List<string> tempDepartureFlightCity = new List<string>();
            List<string> tempArrivalFlightCountry = new List<string>();
            List<string> tempArrivalFlightcity = new List<string>();

            if (flight.ScheduleID != 1)
            {
                List<Aircraft> aircraftList = aircraftContext.GetAllAircrafts();
                List<FlightRoute> flightRouteList = flightRouteContext.GetAllFlightRoutes();
                foreach (Aircraft aircraft in aircraftList)
                {
                    if (flight.AircraftID == aircraft.AircraftID)
                    {
                        tempAircraftId.Add(aircraft.AircraftID);
                        tempAircraftStatus.Add(aircraft.Status);
                        tempDepartureDateTime.Add(flight.DepartureDateTime);
                        tempArrivalDateTime.Add(flight.ArrivalDateTime);

                        foreach (FlightRoute f in flightRouteList)
                        {
                            if (f.RouteID == flight.RouteID)
                            {
                                tempDepartureFlightCity.Add(f.DepartureFlightCity);
                                tempDepartureFlightCountry.Add(f.DepartureFlightCountry);
                                tempArrivalFlightcity.Add(f.DepartureFlightCity);
                                tempArrivalFlightCountry.Add(f.ArrivalFlightCountry);
                                break;
                            }
                        }
                    }
                }

            }
            FlightScheduleViewModel flightVM = new FlightScheduleViewModel
            {
                ScheduleID = flight.ScheduleID,
                //RouteID = flight.RouteID,
                FlightNumber = flight.FlightNumber/*
                AircraftID = tempAircraftId,
                DepartureFlightCity = tempDepartureFlightCity,
                DepartureFlightCountry = tempDepartureFlightCountry,
                ArrivalFlightCity = tempArrivalFlightcity,
                ArrivalFlightCountry = tempArrivalCountry,
                DepartureDateTime = tempDepartureDateTime,
                ArrivalDateTime = tempArrivalDateTime*/

            };
            return flightVM;
            
        }

    }
}

web assignment team 5/Views/Flight/CreateRoute.cshtml
@model web_assignment_team_5.Models.FlightRoute

@{
    ViewData["Title"] = "CreateRoute";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h1>CreateRoute</h1>

<h4>FlightRoute</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRoute">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="DepartureFlightCity" class="control-label"></label>
                <input asp-for="DepartureFlightCity" class="form-control" />
                <span asp-validation-for="DepartureFlightCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartureFlightCountry" class="control-label"></label>
                <input asp-for="DepartureFlightCountry" class="form-control" />
                <span asp-validation-for="DepartureFlightCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArrivalFlightCity" class="control-label"></label>
                <input asp-for="ArrivalFlightCity" class="form-control" />
                <span asp-validation-for="ArrivalFlightCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArrivalFlightCountry" class="control-label"></label>
                <input asp-for="ArrivalFlightCountry" class="form-control" />
                <span asp-validation-for="ArrivalFlightCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightDuration" class="control-label"></label>
                <input asp-for="FlightDuration" class="form-control" />
                <span asp-validation-for="FlightDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <div>
                @Html.ValidationMessage("Route")
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Viewflights">Back to List</a>
</div>

web assignment team 5/Views/Flight/CreateSchedule.cshtml
@model web_assignment_team_5.Models.FlightSchedule

@{
    ViewData["Title"] = "Schedule";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h4 class="PageTitle">Create flight route record</h4>
<h1>Schedule Flight</h1>

<hr />
<form asp-action="CreateSchedule">
    <fieldset class="FormContent">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>


        <div class="form-group row">
            <label asp-for="FlightNumber"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="FlightNumber" type="text" placeholder="LC123" class="form-control" />
                <span asp-validation-for="FlightNumber" class="text-danger"></span>

            </div>
        </div>


        <div class="form-group row">
            <label asp-for="RouteID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <select asp-for="RouteID" asp-items="@ViewData["RouteIDList"] as List<SelectListItem>" class="form-control"></select>
                <span asp-validation-for="RouteID" class="text-danger"></span>

            </div>
        </div>



        <div class="form-group row">
            <label asp-for="DepartureDateTime"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="DepartureDateTime" type="datetime-local" class="form-control" min=@DateTime.Now.Date.AddDays(1) />
                <span asp-validation-for="DepartureDateTime"></span>

            </div>
        </div>

        <div class="form-group row">
            <label asp-for="ArrivalDateTime"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="ArrivalDateTime" type="datetime-local" class="form-control" />
                <span asp-validation-for="ArrivalDateTime" class="text-danger"></span>

            </div>
        </div>

        <div class="form-group row">
            <label asp-for="EconomyClassPrice"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="EconomyClassPrice" type="number" placeholder="0.00" step="0.01" class="form-control" />
                <span asp-validation-for="EconomyClassPrice" class="text-danger"></span>

            </div>
        </div>

        <div class="form-group row">
            <label asp-for="BusinessClassPrice"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="BusinessClassPrice" type="number" placeholder="0.00" step="0.01" class="form-control" />
                <span asp-validation-for="BusinessClassPrice" class="text-danger"></span>

            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Status"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Status" type="text" value="Opened" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>

            </div>
        </div>

            <div class="form-group ">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <div>
                <a asp-action="Viewflights">Back to List</a>
            </div>
</fieldset>
    </form>

web assignment team 5/Views/Flight/Update.cshtml
@model web_assignment_team_5.Models.FlightSchedule

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h1>Update</h1>

<h4>FlightSchedule</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ScheduleID" class="control-label"></label>
                <input asp-for="ScheduleID" readonly class="form-control" />
                <span asp-validation-for="ScheduleID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightNumber" class="control-label"></label>
                <input asp-for="FlightNumber" readonly class="form-control" />
                <span asp-validation-for="FlightNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RouteID" class="control-label"></label>
                <input asp-for="RouteID" readonly class="form-control" />
                <span asp-validation-for="RouteID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AircraftID" class="control-label"></label>
                <input asp-for="AircraftID" readonly class="form-control" />
                <span asp-validation-for="AircraftID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartureDateTime" class="control-label"></label>
                <input asp-for="DepartureDateTime" readonly class="form-control" />
                <span asp-validation-for="DepartureDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArrivalDateTime" class="control-label"></label>
                <input asp-for="ArrivalDateTime" readonly class="form-control" />
                <span asp-validation-for="ArrivalDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EconomyClassPrice" class="control-label"></label>
                <input asp-for="EconomyClassPrice" readonly class="form-control" />
                <span asp-validation-for="EconomyClassPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BusinessClassPrice" class="control-label"></label>
                <input asp-for="BusinessClassPrice" readonly class="form-control" />
                <span asp-validation-for="BusinessClassPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <div class="form-group form-check-inline">
                    <label class="col-form-label">
                        <input asp-for="Status" type="radio" value="Opened" class="form-check-input" />
                        <span style="font-weight:normal; padding-right:20px">Opened</span>
                    </label>
                    <label class="col-form-label">
                        <input asp-for="Status" type="radio" value="Full" class="form-check-input" />
                        <span style="font-weight:normal; padding-right:20px">Full</span>
                    </label>
                    <label class="col-form-label">
                        <input asp-for="Status" type="radio" value="Delayed" class="form-check-input" />
                        <span style="font-weight:normal; padding-right:20px">Delayed</span>
                    </label>
                    <label class="col-form-label">
                        <input asp-for="Status" type="radio" value="Cancelled" class="form-check-input" />
                        <span style="font-weight:normal; padding-right:20px">Cancelled</span>
                    </label>
                </div>
                    <span asp-validation-for="Status" class="text-danger"></span>
                </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Viewflights">Back to List</a>
</div>

web assignment team 5/Views/Flight/ViewScheduleDetails.cshtml
@model web_assignment_team_5.Models.FlightScheduleViewModel

@{
    ViewData["Title"] = "View Routes";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h4 class="PageTitle">View Aircraft Schedule</h4>
<hr />
<fieldset class="FormContent">
    <div class="form-group row">
        <label asp-for="ScheduleID"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("ScheduleID")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="FlightNumber"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("FlightNumber")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="AircraftID"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("AircraftID")
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-3 col-form-label">Flight Schedule: </label>
    </div>
    <div class="table-responsive">
        <table id="viewFlightSchedule" class="table table-striped table-bordered">
            <thead class="thead-light">
                <tr>
                    <th>Departure DateTime</th>
                    <th>Arrival DateTime</th>
                    <th>Departure Country</th>
                    <th>Arrival Country</th>
                </tr>
            </thead>

            
        </table>
    </div>
    <div class="form-group row">
        <div class="col-sm-3 offset-sm-3">
            <a asp-action="ViewFlightSchedule"
               asp-controller="Flight">Back to List</a>
        </div>
    </div>
</fieldset>

web assignment team 5/Views/Flight/Viewflights.cshtml
@model IEnumerable<web_assignment_team_5.Models.FlightRoute>

@{
    ViewData["Title"] = "Viewflights";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h1>Viewflights</h1>

<div>
    <h4>FlightRoute</h4>
    <hr />
    @foreach (var item in Model)
    {
        <div class="table-responsive">
            <table id="Viewflights" class="table table-striped table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            Route ID
                        </th>
                        <th>
                            Departure City
                        </th>
                        <th>
                            Departure Country
                        </th>
                        <th>
                            Arrival City
                        </th>
                        <th>
                            Arrival Country
                        </th>
                        <th>
                            Duration
                        </th>
                    </tr>
                    <tr>
                        <td>
                            @item.RouteID
                        </td>
                        <td>
                            @item.DepartureFlightCity
                        </td>
                        <td>
                            @item.DepartureFlightCountry
                        </td>
                        <td>
                            @item.ArrivalFlightCity
                        </td>
                        <td>
                            @item.ArrivalFlightCountry
                        </td>
                        <td>
                            @item.FlightDuration
                        </td>
                    </tr>
                </thead>
            </table>
        </div>
            
        <table id="Viewflights2" class="table table-striped table-bordered">
            <thead class="thead-light">
                @foreach (var flightSchedules in item.flightSchedules)
                {

                    <tr>
                        <th>
                            Schedule ID
                        </th>
                        <th>
                            Flight Number
                        </th>
                        <th>
                            Route ID
                        </th>
                        <th>
                            Aircraft ID
                        </th>
                        <th>
                            Departure Date and Time
                        </th>
                        <th>
                            Arrival Date and Time
                        </th>
                        <th>
                            Status
                        </th>
                        <th>

                        </th>
                        
                    </tr>
                    <tr>
                        <td>
                            @flightSchedules.ScheduleID
                        </td>
                        <td>
                            @flightSchedules.FlightNumber
                        </td>
                        <td>
                            @flightSchedules.RouteID
                        </td>
                        <td>
                            @flightSchedules.AircraftID
                        </td>
                        <td>
                            @flightSchedules.DepartureDateTime
                        </td>
                        <td>
                            @flightSchedules.ArrivalDateTime
                        </td>
                        <td>
                            @flightSchedules.Status
                        </td>
                        <td>
                            <a asp-action="Update" asp-controller="Flight" asp-route-id="@flightSchedules.ScheduleID">Update Status</a>
                        </td>
                    </tr>
                }
            </thead>
        </table>
        }
</div>