web assignment team 5/Models/Staff.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace web_assignment_team_5.Models
{
    public class Staff
    {
        [Display(Name ="Staff ID")]
        public int StaffID { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "Name is required.")]
        [StringLength(50, ErrorMessage = "Name cannot exceed 50 characters. ")]
        public string StaffName { get; set; }

        public char Gender { get; set; }

        [Display(Name = "Date of Employment")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Date Employed is required.")]
        public DateTime DateEmployed { get; set; }

        [Display(Name = "Vocation")]
        [Required(ErrorMessage = "Vocation is required.")]
        public string Vocation { get; set; }

        [Display(Name = "Email Address")]
        [EmailAddress]
        // Custom Validation Attribute for checking email address exists
        [ValidateEmailExists]
        [StringLength(50, ErrorMessage = "Email address cannot exceed 50 characters. ")]
        [Required(ErrorMessage = "Email Address is required.")]
        public string EmailAddr { get; set; }

        public string Password { get; set; }

        public string Status { get; set; }

    }
}

web assignment team 5/Models/StaffViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace web_assignment_team_5.Models
{
    public class StaffViewModel
    {
        [Display(Name = "ID")]
        public int StaffID { get; set; }

        [Display(Name = "Name")]
        public string StaffName { get; set; }

        [Display(Name = "Gender")]
        public char Gender { get; set; }

        [Display(Name = "Date of Employment")]
        public DateTime DateEmployed { get; set; }

        [Display(Name = "Vocation")]
        public string Vocation { get; set; }

        [Display(Name = "Email Address")]
        public string EmailAddr { get; set; }

        [Display(Name = "Status")]
        public string Status { get; set; }

        public List<int> ScheduleNo { get; set; }

        public List<string> Role { get; set; }

        public List<DateTime> DepartureDateTime { get; set; }

    }
}

web assignment team 5/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using web_assignment_team_5.DAL;
using web_assignment_team_5.Models;


namespace web_assignment_team_5.Controllers
{
    public class StaffController : Controller
    {
        private StaffDAL staffContext = new StaffDAL();
        private FlightCrewDAL flightcrewContext = new FlightCrewDAL();
        private FlightScheduleDAL flightscheduleContext = new FlightScheduleDAL();
        public IActionResult Index()
        {
            // Stop accessing the action if not logged in 
            // or account not in the "Admin" role 
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }

            List<Staff> staffList = staffContext.GetAllStaff();
            return View(staffList);
        }

        // GET: Staff/Create
        public IActionResult Create()
        {
            // Stop accessing the action if not logged in 
            // or account not in the "Admin" role 
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["VocationList"] = GetVocation();
            return View();

        }

        // POST: Staff/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Staff staff)
        {
            //Get vocation list for drop-down list
            //in case of the need to return to Create.cshtml view
            ViewData["VocationList"] = GetVocation();
            if (ModelState.IsValid)
            {
                //Add staff record to database
                staff.StaffID = staffContext.Add(staff);
                //Redirect user to Staff/Index view
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view
                //to display error message
                return View(staff);
            }
        }

        private List<SelectListItem> GetVocation()
        {
            List<SelectListItem> vocation = new List<SelectListItem>();
            vocation.Add(new SelectListItem { Value = "Administrator", Text = "Administrator" });
            vocation.Add(new SelectListItem { Value = "Pilot", Text = "Pilot" });
            vocation.Add(new SelectListItem { Value = "Flight Attendant", Text = "Flight Attendant" });

            return vocation;
        }

        // GET: Staff/Details/5
        public IActionResult Details(int id)
        {
            // Stop accessing the action if not logged in 
            // or account not in the "Admin" role 
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }

            Staff staff = staffContext.GetDetails(id);
            StaffViewModel staffVM = MapToStaffVM(staff);
            return View(staffVM);
        }

        public StaffViewModel MapToStaffVM(Staff staff)
        {
            List<int> tempScheduleNo = new List<int>();
            List<string> tempRole = new List<string>();
            List<DateTime> tempDepartureDateTime = new List<DateTime>();
            if (staff.Vocation != "Administrator")
            {
                List<FlightCrew> flightcrewList = flightcrewContext.GetAllFlightCrew();
                List<FlightSchedule> flightscheduleList = flightscheduleContext.GetAllFlightSchedule();
                foreach (FlightCrew fc in flightcrewList)
                {
                    if (fc.StaffID == staff.StaffID)
                    {
                        tempRole.Add(fc.Role);
                        tempScheduleNo.Add(fc.ScheduleID);
                        foreach (FlightSchedule fs in flightscheduleList)
                        {
                            if (fc.ScheduleID == fs.ScheduleID)
                            {
                                tempDepartureDateTime.Add(fs.DepartureDateTime);
                                break;
                            }
                        }
                    }
                }

            }

            StaffViewModel staffVM = new StaffViewModel
            {
                StaffID = staff.StaffID,
                StaffName = staff.StaffName,
                Gender = staff.Gender,
                DateEmployed = staff.DateEmployed,
                Vocation = staff.Vocation,
                EmailAddr = staff.EmailAddr,
                Status = staff.Status,
                ScheduleNo = tempScheduleNo,
                Role = tempRole,
                DepartureDateTime = tempDepartureDateTime
            };

            return staffVM;
        }

        private List<DateTime> getDepartureDate (Staff s, List<FlightCrew> fcList, List<FlightSchedule> fsList) // get list of depareture date for each staff
        {
            List<DateTime> tempDepartureDateTime = new List<DateTime>();
            if (s.Vocation != "Administrator")
            {
                foreach (FlightCrew fc in fcList)
                {
                    if (fc.StaffID == s.StaffID)
                    {
                        foreach (FlightSchedule fs in fsList)
                        {
                            if (fc.ScheduleID == fs.ScheduleID)
                            {
                                DateTime tempDate = fs.DepartureDateTime.Date;
                                tempDepartureDateTime.Add(tempDate);
                                break;
                            }
                        }
                    }
                }

            }

            return tempDepartureDateTime;
        }

        public IActionResult UpdatePersonnel()
        {
            // Stop accessing the action if not logged in 
            // or account not in the "Admin" role 
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }

            List<Staff> personnelList = new List<Staff>();
            List<Staff> staffList = staffContext.GetAllStaff();
            DateTime currentDate = DateTime.Now.Date;

            List<FlightCrew> flightcrewList = flightcrewContext.GetAllFlightCrew();
            List<FlightSchedule> flightscheduleList = flightscheduleContext.GetAllFlightSchedule();

            foreach (Staff s in staffList)
            {
                bool check = UpdateEligibility(s, currentDate, flightcrewList, flightscheduleList);
                bool assigned = checkAssigned(s, flightcrewList);
                if(check == true)
                {
                    personnelList.Add(s);
                }
                if(assigned == false)
                {
                    personnelList.Add(s);
                }
            }

            return View(personnelList);
        }

        private bool UpdateEligibility(Staff s, DateTime currentDate, List<FlightCrew> fcList, List<FlightSchedule> fsList)
        {
            bool check = false;
            List<DateTime> departureDateList = getDepartureDate(s, fcList, fsList);
            foreach(DateTime tempDate in departureDateList)
            {
                if (tempDate < currentDate)
                {
                    check = true;
                }
                else 
                {
                    check = false;
                    break;
                }
            }
            return check;
        }

        private bool checkAssigned(Staff s, List<FlightCrew> fcList)
        {
            bool check = true; // if its admin 
            if (s.Vocation != "Administrator")
            {
                check = false;
                foreach (FlightCrew fc in fcList)
                {
                    if (s.StaffID == fc.StaffID)
                    {
                        check = true;
                    }
                }
            }
            
            return check;
        }

        // GET: Staff/Edit
        public IActionResult Edit(int? id)
        {
            // Stop accessing the action if not logged in 
            // or account not in the "Admin" role 
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            { //Query string parameter not provided 
                //Return to listing page, not allowed to edit 
                return RedirectToAction("Index");
            }
            Staff staff = staffContext.GetDetails(id.Value);
            if (staff == null)
            { //Return to listing page, not allowed to edit 
                return RedirectToAction("Index");
            }
            return View(staff);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Staff staff)
        {
            if (ModelState.IsValid)
            {
                //Update staff record to database
                staffContext.Update(staff);
                return RedirectToAction("UpdatePersonnel");
            }
            else
            {
                //Input validation fails, return to the view
                //to display error message
                return View(staff);
            }
        }

web assignment team 5/Views/Staff/AssignSchedule.cshtml
@model IEnumerable<web_assignment_team_5.Models.FlightSchedule>

@{
    ViewData["Title"] = "AssignSchedule";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h4 class="PageTitle">Unassigned Schedule</h4>

@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewStaff" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Flight Number</th>
                    <th>Departure DateTime</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ScheduleID.ToString()</td>
                        <td>@item.FlightNumber</td>
                        <td>@item.DepartureDateTime.ToString()</td>
                        <td>
                            <a asp-action="FlightCaptain" asp-controller="Staff" asp-route-id="@item.ScheduleID">Assign Personnel</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red">No record found!</span>
}

web assignment team 5/Views/Staff/CabinCrewLeader.cshtml
@model web_assignment_team_5.Models.FlightCrew

@{
    ViewData["Title"] = "CabinCrewLeader";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}


<h4>Cabin Crew Leader</h4>
<hr />
<form asp-action="CabinCrewLeader">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="ScheduleID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="ScheduleID" value="@Model.ScheduleID" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Role" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Role" value="@Model.Role" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="StaffID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <select asp-for="StaffID"
                        asp-items="@ViewData["FlightAttendantList"] as List<SelectListItem>"
                        class="form-control">
                </select>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </div>
    </fieldset>
</form>

web assignment team 5/Views/Staff/Create.cshtml
@model web_assignment_team_5.Models.Staff

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h4 class="PageTitle">Create Flight Personnel Record</h4>
<hr />
<form asp-action="Create">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="StaffName" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="StaffName" class="form-control" />
                <span asp-validation-for="StaffName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Gender" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <div class="form-group form-check-inline">
                    <label class="col-form-label">
                        <input asp-for="Gender" type="radio" value="M" checked class="form-check-input" />
                        <span style="font-weight:normal; padding-right:20px">Male</span>
                    </label>
                    <label class="col-form-label">
                        <input asp-for="Gender" type="radio" value="F" class="form-check-input" />
                        <span style="font-weight:normal; padding-right:20px">Female</span>
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="DateEmployed" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="DateEmployed" class="form-control" />
                <span asp-validation-for="DateEmployed" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Vocation" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <select asp-for="Vocation"
                        asp-items="@ViewData["VocationList"] as List<SelectListItem>"
                        class="form-control">
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="EmailAddr" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="EmailAddr" class="form-control" />
                <span asp-validation-for="EmailAddr" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row"> 
            <div class="col-sm-9 offset-sm-3"> 
                <input type="submit" value="Create" class="btn btn-primary" /> 
            </div> 
        </div>
    </fieldset>
</form>

web assignment team 5/Views/Staff/Details.cshtml
@model web_assignment_team_5.Models.StaffViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h4 class="PageTitle">View Personnel Details</h4>
<hr />
<fieldset class="FormContent">
    <div class="form-group row">
        <label asp-for="StaffID"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("StaffID")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="StaffName"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("StaffName")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Gender" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <div class="form-group form-check-inline">
                <label class="col-form-label">
                    <input asp-for="Gender" type="radio" value="M" class="form-check-input" disabled />
                    <span style="font-weight:normal; padding-right:20px">Male</span>
                </label>
                <label class="col-form-label">
                    <input asp-for="Gender" type="radio" value="F" class="form-check-input" disabled />
                    <span style="font-weight:normal; padding-right:20px">Female</span>
                </label>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="DateEmployed"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("DateEmployed")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Vocation"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("Vocation")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="EmailAddr"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("EmailAddr")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Status"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("Status")
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-3 col-form-label">Flight Schedule: </label>
    </div>
    <div class="table-responsive">
        <table id="viewFlightSchedule" class="table table-striped table-bordered">
            <thead class="thead-light">
                <tr>
                    <th>Flight No.</th>
                    <th>Role</th>
                    <th>Departure DateTime</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.ScheduleNo.Count; i++)
                {
                    <tr>
                        <td>@Model.ScheduleNo[i]</td>
                        <td>@Model.Role[i]</td>
                        <td>@Model.DepartureDateTime[i]</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="form-group row"> 
        <div class="col-sm-3"> 
            <a asp-action="Index" 
               asp-controller="Staff">Back to List</a> 
        </div> 
    </div>
</fieldset>

web assignment team 5/Views/Staff/Edit.cshtml
@model web_assignment_team_5.Models.Staff

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h4 class="PageTitle">Edit Staff Record</h4>
<hr />
<form asp-action="Edit">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="StaffID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="StaffID" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="StaffName" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="StaffName" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="DateEmployed" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="DateEmployed" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Vocation" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Vocation" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="EmailAddr" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="EmailAddr" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Status" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <div class="form-group form-check-inline">
                    <label class="col-form-label">
                        <input asp-for="Status" type="radio" value="Active" class="form-check-input" />
                        <span style="font-weight:normal; padding-right:20px">Active</span>
                    </label>
                    <label class="col-form-label">
                        <input asp-for="Status" type="radio" value="Inactive" class="form-check-input" />
                        <span style="font-weight:normal; padding-right:20px">Inactive</span>
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="UpdatePersonnel">Back to List</a>
        </div>
    </fieldset>
</form>

web assignment team 5/Views/Staff/FlightAttendant_1.cshtml
@model web_assignment_team_5.Models.FlightCrew

@{
    ViewData["Title"] = "FlightAttendant_1";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}


<h4>Flight Attendant #1</h4>
<hr />
<form asp-action="FlightAttendant_1">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="ScheduleID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="ScheduleID" value="@Model.ScheduleID" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Role" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Role" value="@Model.Role" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="StaffID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <select asp-for="StaffID"
                        asp-items="@ViewData["FlightAttendantList"] as List<SelectListItem>"
                        class="form-control">
                </select>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </div>
    </fieldset>
</form>

web assignment team 5/Views/Staff/FlightAttendant_2.cshtml
@model web_assignment_team_5.Models.FlightCrew

@{
    ViewData["Title"] = "FlightAttendant_2";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}


<h4>Flight Attendant #2</h4>
<hr />
<form asp-action="FlightAttendant_2">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="ScheduleID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="ScheduleID" value="@Model.ScheduleID" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Role" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Role" value="@Model.Role" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="StaffID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <select asp-for="StaffID"
                        asp-items="@ViewData["FlightAttendantList"] as List<SelectListItem>"
                        class="form-control">
                </select>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </div>
    </fieldset>
</form>

web assignment team 5/Views/Staff/FlightAttendant_3.cshtml
@model web_assignment_team_5.Models.FlightCrew

@{
    ViewData["Title"] = "FlightAttendant_3";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}


<h4>Flight Attendant #3</h4>
<hr />
<form asp-action="FlightAttendant_3">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="ScheduleID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="ScheduleID" value="@Model.ScheduleID" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Role" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Role" value="@Model.Role" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="StaffID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <select asp-for="StaffID"
                        asp-items="@ViewData["FlightAttendantList"] as List<SelectListItem>"
                        class="form-control">
                </select>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Done" class="btn btn-primary" />
            </div>
        </div>
    </fieldset>
</form>

web assignment team 5/Views/Staff/UpdatePersonnel.cshtml
@model IEnumerable<web_assignment_team_5.Models.Staff>

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h4 class="PageTitle">Update Flight Personnel Status</h4>

@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewStaff" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Staff Name</th>
                    <th>Email Address</th>
                    <th>Vocation</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.StaffID.ToString()</td>
                        <td>@item.StaffName</td>
                        <td>@item.EmailAddr</td>
                        <td>@item.Vocation</td>
                        <td>@item.Status</td>
                        <td>
                            <a asp-action="Edit" asp-controller="Staff" asp-route-id="@item.StaffID">Edit</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red">No record found!</span>
}

web assignment team 5/Views/Staff/_ViewStaff.cshtml
@model IEnumerable<web_assignment_team_5.Models.Staff>

@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewStaff" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Staff Name</th>
                    <th>Email Address</th>
                    <th>Vocation</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.StaffID.ToString()</td>
                        <td>@item.StaffName</td>
                        <td>@item.EmailAddr</td>
                        <td>@item.Vocation</td>
                        <td>@item.Status</td>
                        <td>
                            <a asp-action="Details" asp-controller="Staff" asp-route-id="@item.StaffID">Details</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else{ 
    <span style="color:red">No record found!</span>
}