web assignment team 5/Models/Aircraft.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace web_assignment_team_5.Models
{
    public class Aircraft
    {
        [Display(Name = "Aircraft ID")]
        public int AircraftID { get; set; }

        [Display(Name = "Aircraft Model")]
        [Required(ErrorMessage = "Please enter the Aircraft Model.")]
        public string MakeModel { get; set; }

        [Display(Name = "Number of Economy Seats")]
        [Required(ErrorMessage = "Please enter the number of Economy Seats.")]
        public int? NumEconomySeat { get; set; }

        [Display(Name = "Number of Business Seats")]
        [Required(ErrorMessage = "Please enter the number of Business Seats.")]
        public int? NumBusinessSeat { get; set; }

        [Display(Name = "Date of Last Maintenance")]
        [DataType(DataType.Date)]
        public DateTime? DateLastMaintenance { get; set; }

        [Display(Name = "Status")]
        public string Status { get; set; } = "Operational";
    }
}

web assignment team 5/Models/AircraftViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace web_assignment_team_5.Models
{
    public class AircraftViewModel
    {
        [Display(Name = "ID")]
        public int AircraftID { get; set; }

        [Display(Name = "Aircraft Model")]
        public string MakeModel { get; set; }

        [Display(Name = "Departure DateTime")]
        public List<DateTime> DepartureDateTime { get; set; }

        [Display(Name = "Arrival DateTime")]
        public List<DateTime> ArrivalDateTime { get; set; }

        [Display(Name = "Departure Country")]
        public List<string> DepartureCountry { get; set; }

        [Display(Name = "Arrival Country")]
        public List<string> ArrivalCountry { get; set; }

    }
}

web assignment team 5/Controllers/AircraftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.DataProtection.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using web_assignment_team_5.DAL;
using web_assignment_team_5.Models;

namespace web_assignment_team_5.Controllers
{
    public class AircraftController : Controller
    {
        private AircraftDAL aircraftContext = new AircraftDAL();
        private FlightScheduleDAL flightScheduleContext = new FlightScheduleDAL();
        private FlightRouteDAL flightRouteContext = new FlightRouteDAL();

        // GET: Aircraft
        public IActionResult ViewAircrafts()
        {
            if((HttpContext.Session.GetString("Role") == null) || 
               (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("ViewAircrafts");
            }

            List<Aircraft> aircraftList = aircraftContext.GetAllAircrafts();
            return View(aircraftList);
        }

        // GET: Aircraft/Details/5
        public IActionResult AircraftSchedule(int id)
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("ViewAircrafts");
            }
            Aircraft aircraft = aircraftContext.GetDetails(id);
            AircraftViewModel aircraftVM = MapToAircraftVM(aircraft);
            return View(aircraftVM);
        }

        public AircraftViewModel MapToAircraftVM(Aircraft aircraft)
        {
            List<DateTime> tempDepartureDateTime = new List<DateTime>();
            List<DateTime> tempArrivalDateTime = new List<DateTime>();
            List<string> tempDepartureCountry = new List<string>();
            List<string> tempArrivalCountry = new List<string>();

            if(aircraft.AircraftID != 0)
            {
                List<FlightSchedule> flightScheduleList = flightScheduleContext.GetAllFlightSchedule();
                List<FlightRoute> flightRouteList = flightRouteContext.GetAllFlightRoutes();
                foreach (FlightSchedule flightSched in flightScheduleList)
                {
                    if (flightSched.AircraftID == aircraft.AircraftID)
                    {
                        tempDepartureDateTime.Add(flightSched.DepartureDateTime);
                        tempArrivalDateTime.Add(flightSched.ArrivalDateTime);

                        foreach(FlightRoute f in flightRouteList)
                        {
                            if (f.RouteID == flightSched.RouteID)
                            {
                                        
                                tempDepartureCountry.Add(f.DepartureFlightCountry);
                                tempArrivalCountry.Add(f.ArrivalFlightCountry);
                                break;
                            }
                        }
                    }
                }
            }

            AircraftViewModel aircraftVM = new AircraftViewModel
            {
                AircraftID = aircraft.AircraftID,
                MakeModel = aircraft.MakeModel,
                DepartureDateTime = tempDepartureDateTime,
                ArrivalDateTime = tempArrivalDateTime,
                DepartureCountry = tempDepartureCountry,
                ArrivalCountry = tempArrivalCountry

            };
            return aircraftVM;
        }

               
        // GET: Aircraft/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Aircraft/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Aircraft aircraft)
        {
            if (ModelState.IsValid)
            {
                aircraft.AircraftID = aircraftContext.Add(aircraft);
                return RedirectToAction("ViewAircrafts");
            }
            else
            {
                return View(aircraft);
            }
        }

        public IActionResult CreateAircraft()
        {
            return View();
        }

        public IActionResult UpdateAircraft()
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            
            List<Aircraft> acList = aircraftContext.GetAllAircrafts();
            List<FlightSchedule> fsList = flightScheduleContext.GetAllFlightSchedule();
            List<Aircraft> aircraftList = new List<Aircraft>();
            
            foreach(Aircraft ac in acList)
            {
                aircraftList.Add(ac);
                foreach(FlightSchedule fs in fsList)
                {
                    if((fs.AircraftID == ac.AircraftID) && (ac.Status == "Operational") && (fs.DepartureDateTime >= DateTime.Now) )
                    {
                        aircraftList.Remove(ac);
                    }
                }
            }
            
            return View(aircraftList);
            
        }

        public IActionResult UpdateAircraftFiltered()
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            
            DateTime thirtydays = DateTime.Now.AddDays(-30);
            List<Aircraft> aircraftFiltered = new List<Aircraft>();
            List<Aircraft> aircraftList = aircraftContext.GetAllAircrafts();
            List<FlightSchedule> fsList = flightScheduleContext.GetAllFlightSchedule();

            //Filters to only aircrafts with last maintenance more than 30 days ago and displays it after button is clicked
            foreach (Aircraft ac in aircraftList)
            {
                aircraftFiltered.Add(ac);
                foreach (FlightSchedule fs in fsList)
                {
                    if (ac.DateLastMaintenance > thirtydays || ((fs.AircraftID == ac.AircraftID) && (ac.Status == "Operational") && (fs.DepartureDateTime >= DateTime.Now)))
                    {
                        aircraftFiltered.Remove(ac);
                    }
                }
            }

            return View(aircraftFiltered);
        }

        // GET: Aircraft/Edit/5
        public ActionResult EditAircraft(int? id)
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            { //Query string parameter not provided
              //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            //ViewData["BranchList"] = GetAllBranches();
            Aircraft aircraft = aircraftContext.GetDetails(id.Value);
            if (aircraft == null) {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            return View(aircraft);
        }

        // POST: Aircraft/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditAircraft(Aircraft aircraft)
        {
            if (ModelState.IsValid) {
            //Update staff record to database
                aircraftContext.Update(aircraft);
                return RedirectToAction("UpdateAircraft");
            }
            else {
            //Input validation fails, return to the view
            //to display error message

                return View(aircraft);
            }   
             
        }

        public IActionResult AssignSchedule()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }

            List<FlightSchedule> scheduleNotAssigned = new List<FlightSchedule>();
            List<Aircraft> acList = aircraftContext.GetAllAircrafts();
            List<FlightSchedule> fsList = flightScheduleContext.GetAllFlightSchedule();
            DateTime today = DateTime.Now;

            //Checks if aircraftID matches with schedule and if departuredate is before today and removes it from list
            foreach(FlightSchedule fs in fsList)
            {
                scheduleNotAssigned.Add(fs);
                foreach(Aircraft ac in acList)
                {
                    if ((fs.AircraftID == ac.AircraftID) || (fs.DepartureDateTime < today.Date))
                    {
                        scheduleNotAssigned.Remove(fs);
                    }
                }
            }

            return View(scheduleNotAssigned);
        }

        private List<Aircraft> GetAllAircrafts()
        {
            List<Aircraft> aircraftList = new List<Aircraft>();
            List<Aircraft> acList = aircraftContext.GetAllAircrafts();
            foreach(Aircraft ac in acList)
            {
                if (ac.Status == "Operational")
                {
                    aircraftList.Add(ac);
                }
            }

            aircraftList.Insert(0, new Aircraft
            {
                AircraftID = 0,
                MakeModel = "--Select--"
            });
            return aircraftList;
        }

        public ActionResult AssignAircraft(int? id)
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            { //Query string parameter not provided
              //Return to listing page, not allowed to edit

web assignment team 5/Views/Aircraft/AircraftSchedule.cshtml
@model web_assignment_team_5.Models.AircraftViewModel

@{
    ViewData["Title"] = "Aircraft Schedule";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h4 class="PageTitle">View Aircraft Schedule</h4>
<hr />
<fieldset class="FormContent">
    <div class="form-group row">
        <label asp-for="AircraftID"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("AircraftID")
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="MakeModel"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("MakeModel")
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-3 col-form-label">Aircraft Flight Schedule: </label>
    </div>
    <div class="table-responsive">
        <table id="viewAircraftSchedule" class="table table-striped table-bordered">
            <thead class="thead-light">
                <tr>
                    <th>Departure DateTime</th>
                    <th>Arrival DateTime</th>
                    <th>Departure Country</th>
                    <th>Arrival Country</th>
                </tr>
            </thead>

            <tbody>
                @for (int x = 0; x < Model.ArrivalDateTime.Count; x++)
                {
                    <tr>
                        <td>@Model.DepartureDateTime[x]</td>
                        <td>@Model.ArrivalDateTime[x]</td>
                        <td>@Model.DepartureCountry[x]</td>
                        <td>@Model.ArrivalCountry[x]</td>
                    </tr>

                }

            </tbody>
        </table>
    </div>
    <div class="form-group row">
        <div class="col-sm-3 offset-sm-3">
            <a asp-action="ViewAircrafts"
               asp-controller="Aircraft">Back to List</a>
        </div>
    </div>
</fieldset>

web assignment team 5/Views/Aircraft/AssignAircraft.cshtml
@model web_assignment_team_5.Models.FlightSchedule

@{
    ViewData["Title"] = "AssignAircraft";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h4>Assign Aircraft</h4>
<hr />
<form asp-action="AssignAircraft">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="ScheduleID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="ScheduleID" value="@Model.ScheduleID" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="FlightNumber" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="FlightNumber" value="@Model.FlightNumber" readonly class="form-control-plaintext" />
            </div>
        </div>


        <div class="form-group row">
            <label asp-for="AircraftID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <select asp-for="AircraftID"
                        asp-items="@(new SelectList(
                                     @ViewData["AircraftList"] as List <Aircraft>,
                                     "AircraftID", "MakeModel"))"
                        class="form-control"></select>

            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="AssignSchedule">Back to List</a>
        </div>
    </fieldset>
</form>
    

web assignment team 5/Views/Aircraft/AssignSchedule.cshtml
@model IEnumerable<web_assignment_team_5.Models.FlightSchedule>

@{
    ViewData["Title"] = "AssignSchedule";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h4 class="PageTitle">Unassigned Schedule</h4>

@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewStaff" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Flight Number</th>
                    <th>Departure DateTime</th>
                    <th>Arrival DateTime</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ScheduleID</td>
                        <td>@item.FlightNumber</td>
                        <td>@item.DepartureDateTime</td>
                        <td>@item.ArrivalDateTime</td>
                        <td>
                            <a asp-action="AssignAircraft" asp-controller="Aircraft" asp-route-id="@item.ScheduleID">Assign Aircraft</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red">No record found!</span>
}

web assignment team 5/Views/Aircraft/CreateAircraft.cshtml
@model web_assignment_team_5.Models.Aircraft

@{
    ViewData["Title"] = "CreateAircraft";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}


<h4 class="PageTitle">Create Aircraft Record</h4>
<hr />
<form asp-action="Create">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="MakeModel"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="MakeModel" class="form-control" required />
                <span asp-validation-for="MakeModel"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="NumEconomySeat"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="NumEconomySeat" class="form-control" type="number" required />
                <span asp-validation-for="NumEconomySeat"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="NumBusinessSeat"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="NumBusinessSeat" class="form-control" type="number" required />
                <span asp-validation-for="NumBusinessSeat"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="DateLastMaintenance"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="DateLastMaintenance" class="form-control" type="date" />
                <span asp-validation-for="DateLastMaintenance"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Create"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="ViewAircrafts">Back to List</a>
        </div>

    </fieldset>
</form>

web assignment team 5/Views/Aircraft/EditAircraft.cshtml
@model web_assignment_team_5.Models.Aircraft

@{
    ViewData["Title"] = "EditAircraft";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h4 class="PageTitle">Edit Aircraft Status</h4>
<hr />
<form asp-action="EditAircraft">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="MakeModel"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="MakeModel" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="NumEconomySeat"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="NumEconomySeat" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="NumBusinessSeat"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="NumBusinessSeat" readonly class="form-control-plaintext" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="DateLastMaintenance"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="DateLastMaintenance" readonly class="form-control-plaintext" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Status"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <label> <input asp-for="Status" class="form-control-plaintext" type="radio" value="Operational" name="stat" /> Operational</label>
                <label> <input asp-for="Status" class="form-control-plaintext" type="radio" value="Under Maintenance" name="stat" /> Under Maintenance</label>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Save"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="UpdateAircraft">Back to List</a>
        </div>
    </fieldset>
</form>

web assignment team 5/Views/Aircraft/UpdateAircraft.cshtml
@model IEnumerable<web_assignment_team_5.Models.Aircraft>

@{
    ViewData["Title"] = "UpdateAircraft";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h4 class="PageTitle">Update Aircraft Status</h4>

@if (Model.ToList().Count > 0)
{
    <div class="form-group row">
        <div class="col-sm-9 offset-sm-3">
            <input type="button" value="Last Maintained > 30 Days"
                   class="btn btn-primary" onclick="location.href='@Url.Action("UpdateAircraftFiltered", "Aircraft")'" style="float:right"/>
        </div>
    </div>
    <div class="table-responsive">
        <table id="viewAircraft" class="table table-striped table-bordered">
            <thead class="thead-dark">

                <tr>
                    <th>ID</th>
                    <th>Model</th>
                    <th>No. Economy Seats</th>
                    <th>No. Business Seats</th>
                    <th>Date of Last Maintenance</th>
                    <th>Status</th>
                    <th>Update</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.AircraftID.ToString()</td>
                        <td>@item.MakeModel.ToString()</td>
                        <td>@item.NumEconomySeat.ToString()</td>
                        <td>@item.NumBusinessSeat.ToString()</td>
                        <td>@item.DateLastMaintenance.ToString()</td>
                        <td>@item.Status.ToString()</td>
                        <td><a asp-action="EditAircraft" asp-controller="Aircraft" asp-route-id="@item.AircraftID">Update</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red">No record found!</span>
}

web assignment team 5/Views/Aircraft/UpdateAircraftFiltered.cshtml
@model IEnumerable<web_assignment_team_5.Models.Aircraft>

@{
    ViewData["Title"] = "UpdateAircraft";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h4 class="PageTitle">Update Aircraft Status</h4>

@if (Model.ToList().Count > 0)
{
    <div class="form-group row">
        <div class="col-sm-9 offset-sm-3">
            <input type="button" value="All"
                   class="btn btn-primary" onclick="location.href='@Url.Action("UpdateAircraft", "Aircraft")'" style="float:right"/>
        </div>
    </div>
    <div class="table-responsive">
        <table id="viewAircraft" class="table table-striped table-bordered">
            <thead class="thead-dark">

                <tr>
                    <th>ID</th>
                    <th>Model</th>
                    <th>No. Economy Seats</th>
                    <th>No. Business Seats</th>
                    <th>Date of Last Maintenance</th>
                    <th>Status</th>
                    <th>Update</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.AircraftID.ToString()</td>
                        <td>@item.MakeModel.ToString()</td>
                        <td>@item.NumEconomySeat.ToString()</td>
                        <td>@item.NumBusinessSeat.ToString()</td>
                        <td>@item.DateLastMaintenance.ToString()</td>
                        <td>@item.Status.ToString()</td>
                        <td><a asp-action="EditAircraft" asp-controller="Aircraft" asp-route-id="@item.AircraftID">Update</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red">No record found!</span>
}

web assignment team 5/Views/Aircraft/ViewAircrafts.cshtml
@model IEnumerable<web_assignment_team_5.Models.Aircraft>

@{
    ViewData["Title"] = "ViewAircrafts";
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
}

<h1>View Aircrafts</h1>
<partial name="~/Views/Aircraft/_ViewAircraft.cshtml" model="@Model" />

web assignment team 5/Views/Aircraft/_ViewAircraft.cshtml
@model IEnumerable<web_assignment_team_5.Models.Aircraft>


@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewAircraft" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th colspan="2">Aircraft</th>
                    <th>Flight Schedule</th>
                </tr>
                <tr>
                    <th>ID</th>
                    <th>Model</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.AircraftID.ToString()</td>
                        <td>@item.MakeModel.ToString()</td>
                        <td><a asp-action="AircraftSchedule" asp-controller="Aircraft" asp-route-id="@item.AircraftID">View Schedule</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red">No record found!</span>
}